### ISSUE TITLE
[PUB] Provide publisher_date in yyyy-mm-dd format for all Publinova sources

### ISSUE THREAD

**Issue by fako** [surfedushare/harvester#140]
Analyse the current formats and see if we can parse the delivered formats into a consistent format. The format should be yyyy-mm-dd (for sorting purposes). Be aware that a source may provide dd-mm-yyyy as well as mm-dd-yyyy. If that is the case we should communicate before moving forward. If they currently provide dates we can work with we may assume they remain that way. If sources don't provide a day or month we can fill out 01.

An example where we already do this is Hanze (can probably be copied to HvA and BUAS). For the rest we often only pick the year from a delivered date. Instead we should parse those dates.

Excluded sources: Sharekit, AnatomyTOOL and Edurep
But please analyse the output for Sharekit. Is it already in yyyy-mm-dd format? If not then we should not change anything and discuss with Sharekit/Edusources before making changes for Publinova.

It would be a good idea to copy the publisher_date value into published_at. We want to migrate to the name "published_at" over time and this is a good first step.

**Comment by fako** [comment]
This command will fetch all data from Sharekit. You can give it other sources to harvest those. With the get_harvest_seeds you can see how it extracts dates.

```
python manage.py harvest_metadata --repository sharekit.SharekitMetadataResource
```

Then with the following command

```
python manage.py shell
```

You'll get access to

```
from harvester.utils.extraction import get_harvest_seeds
get_harvest_seeds("sharekit.SharekitMetadataResource", "edusources", <datetime>)
```

**Comment by fako** [comment]
Is deze nu onder testing? Deadline voor definitieve versie is 9 oktober. Dat lijkt mij realistisch @kallepronk

**Comment by mlagerwerf** [comment]
Test OK, geen bijzonderheden gevonden.

**Comment by fako** [comment]
Deployed to prod @mlagerwerf @kallepronk @peterdubbeldsurf
