### ISSUE TITLE
[PUB] As a user I want DOI's to resolve against the simple DOI resolve service

### ISSUE THREAD

**Issue by fako** [surfedushare/harvester#156]
DOI's moeten gestandaardiseerd worden. Een DOI identifier begint altijd met "10.". Dus kunnen we als volgt standaardiseren

1.   ga van voor op zoek naar “10.” Bij niet vinden niet doorgeven
2.   gooi alles voor de “10.” weg
3.   sla de doi waarde op in het doi veld

Deze stappen moeten plaatsvinden voor alle bronnen. Check even per bron welke variaties er in DOI bestaan. Als het allemaal al begint met "10." hoef je niets te doen (bijvoorbeeld het geval bij Sharekit)

Daarnaast moet ook de search client worden aangepast. De ResearchProductSerializer moet “https://doi.org/” toevoegen aan de output van het doi veld. Dat betekent dat de DOI moet verdwijnen uit de base serializer: https://github.com/surfedushare/search-client/blob/master/search_client/serializers.py#L29

En toegevoegd aan [SimpleLearningMaterial](https://github.com/surfedushare/search-client/blob/master/search_client/serializers.py#L45) en [ResearchProduct](https://github.com/surfedushare/search-client/blob/master/search_client/serializers.py#L70). Waarbij de laatste dus het domein moet prefixen.

Uiteindelijke wens is dat de volgende endpoints allemaal een DOI teruggeven met domein prefix.
* https://harvester.acc.publinova.nl/api/v1/document/oai%3Arepository.han.nl%3A20.500.12470%252F2253/
* https://harvester.acc.publinova.nl/api/v1/document/48b941c9-fd4e-4cbd-9553-f2d8ce422e9a/
* https://harvester.acc.publinova.nl/api/v1/document/67253771-ff85-44cc-8789-28cac205e222/

Terwijl de volgende data agnostisch blijft over welke resolver gebruikt wordt voor de DOI's
* https://harvester.acc.publinova.nl/api/v1/document/raw/oai%3Arepository.han.nl%3A20.500.12470%252F2253/
* https://harvester.acc.publinova.nl/api/v1/document/raw/48b941c9-fd4e-4cbd-9553-f2d8ce422e9a/
* https://harvester.acc.publinova.nl/api/v1/document/raw/67253771-ff85-44cc-8789-28cac205e222/

En de Edusources data moet altijd zonder domein zijn:
* https://harvester.acc.surfedushare.nl/api/v1/document/b65ed260-440a-4bef-b5a0-35d3b5d4dc3e/

**Comment by fako** [comment]
```
from core.models import DatasetVersion, Document
from collections import Counter

dv = DatasetVersion.objects.get_current_version()
Counter([doc.properties["consortium"] for doc in Document.objects.filter(dataset_version=dv)])
```

Output

```
Counter({'Veterinary online collection': 12,
         None: 430,
         'Community Urban Resilience Engineering': 182,
         'Domein Applied Science': 23,
         'Samen HBO-V': 158,
         'Stimuleringsregeling Open en Online Onderwijs': 1240,
         'Projectgroep Vaktherapie': 41,
         'Community Ethics': 105,
         'CyberSecurity': 2,
         'Information Literacy': 457,
         'Project Wiskunde': 2,
         'Zone: naar digitale (open) leermaterialen': 1,
         'Project Structured Exercise Repository with Feedback (SERF)': 1,
         'AnatomyTOOL': 4661})
```

@kallepronk even een voorbeeld van hoe je analyses kunt uitvoeren. De "current dataset version" bevat alle documents, die afgelopen nacht zijn binnengekomen. Vervolgens kun je filteren zoals Django querysets filtered. Zoiets als `doc.properties["doi"][:3]` i.p.v. `doc.properties["consortium"]` geeft een beeld van de DOI's die je kunt verwachten, zonder alle individuele DOI's te listen.

Dit zijn de commands om met acceptance te verbinden voor Edusources. Vergeet daarbij niet je VPN aan te zetten!

```
APPLICATION_MODE=acceptance fab -H bastion.acc.surfedushare.nl hrv.connect-with-shell edusources
```

Of Publinova

```
APPLICATION_PROJECT=publinova APPLICATION_MODE=acceptance fab -H bastion.acc.surfedushare.nl hrv.connect-with-shell publinova
```

Overigens kan je met de volgende commands de data lokaal downloaden en ermee werken. Mocht je dat fijner vinden.

```
invoke hrv.load-data --dataset=delta --source=acceptance
```

En voor Publinova is dat dan:
```
APPLICATION_PROJECT=publinova invoke hrv.load-data --dataset=delta --source=acceptance
```

**Comment by fako** [comment]
Dit is nog wat meer informatie over hoe je Django kunt gebruiken om data te filteren: https://docs.djangoproject.com/en/3.2/ref/models/querysets/

En dit is speciaal voor de JSONB velden die we gebruiken ("properties"): https://docs.djangoproject.com/en/3.2/topics/db/queries/#querying-jsonfield

@kallepronk

**Comment by fako** [comment]
Een problematische DOI: "https://doi.org/10.1080/13814788.2016.1267724. [Epub ahead of print]"

**Comment by fako** [comment]
Relevante publinova bronnen:
- [ ] HvA
- [ ] HKU
- [ ] BUAS
- [x] Sharekit
- [ ] Hanze
- [ ] VHL
- [ ] HAN

**Comment by fako** [comment]
@kallepronk kun jij ter dubbelcheck de bronnen die gedaan zijn hierboven afvinken?
@mlagerwerf ready for testing. In de beschrijving staan links naar de API, die mijns inziens relevant zijn.

**Comment by mlagerwerf** [comment]
Test OK, geen bijzonderheden gezien.

**Comment by fako** [comment]
@mlagerwerf @peterdubbeldsurf deployed to prod. Example: https://harvester.prod.publinova.nl/api/v1/document/5564dad8-b527-431f-a89b-4c71c13a0c5e/
