### ISSUE TITLE
Connect Edurep

### ISSUE THREAD

**Issue by fako** [surfedushare/harvester#188]
Currently the Edurep is only harvested by the legacy harvest process. The goal of this issue is to harvest it with the new harvest process as well. I'll write down some steps, not to tell you what to do, but to guide you into how the system works at the moment.

These steps look a bit weird at first, but are also necessary for preparation. We can pair code these if you want to:
- [x] Copy edurep/models.py to sources/models/edurep.py. We'll be using the XML connection and not JSON.
- [x] Makemigrations and run migrations. Please run makemigrations with "-n edurep" or something else that's readable.
- [x] Register the OAI-PMH Resource with the sources admin
- [x] Copy edurep/tests/factories.py to sources/factories/edurep/extraction.py
- [x] Copy edurep/fixtures/edurep-oaipmh.initial.0.xml to sources/fixtures/fixture.edurep.initial.0.xml
- [x] Check that it's possible to use the factory from sources. If you call create_common_edurep_responses. Is it creating resources? Can you use resource.content? You'll need to adjust at least the body property before this actually works.
- [x] APPLICATION_MODE=production invoke aws.sync-repository-state --push (check if others updated the fixtures before doing this)

Finally these steps will implement the actual metadata extraction for products and files. It's recommended to first work on products:
- [x] Create an edurep.py file in \<entity-django-app\>/sources/ and add the OBJECTIVE from edurep/extraction.py. You will have to copy the extractor class as well
- [x] Create a SEEDING_PHASES list that specifies how seeds can be created from potentially multiple resources/objectives and/or operations
- [x] From here you can add tests similar to \<entity-django-app\>/tests/seeding/test_sharekit.py to test how extraction is functioning.

The following objective keys can be deleted/modified for new-style product objectives, because we handle the requirements for these keys differently with the new harvester setup. Tests related to these objectives can be deleted/modified.
* URL moves to files entity and extraction should be tested there
* files only need to return the URL (and files app will handle details)
* mime_type moves to files entity and extraction should be tested there
* technical_type moves to files entity under the field "type" and extraction should be tested there
* lowest_educational_level can be deleted
* from_youtube can be deleted
* is_restricted can be deleted
* analysis_allowed can be deleted
* any access_rights testing needs to move to files entity
* "complete_set" and "partial_set" tests can be removed. Instead we want tests like TestSharekitProductSeeding for each source and entity

There is also a list of product objective keys that will be nested under the "learning_material" or "research_product" dictionaries. Please see products/sources/sharekit.py for the syntax for these keys (they start with learning_material and research_product respectively).

**Comment by kallepronk** [comment]
is_part_of en has_parts zijn "not currently supported" Is dat nog steeds zo?

**Comment by fako** [comment]
Ja, niet ondersteund door Edurep

**Comment by fako** [comment]
SRN is \<source\>:\<set_name\>:\<external_id\>. Maar ik zie nu \<set\>:\<set\>:\<external_id\>
RESOLVED

**Comment by fako** [comment]
L4L heeft een hoop in-active materialen. Dit zou niet mogen voor L4L, dat zijn altijd WO materialen. Waarschijnlijk nu duidelijker in de nieuwe harvester, maar ook al een probleem in de oude harvester. Even kijken hoe we die gaan tackelen.
RESOLVED

**Comment by fako** [comment]
The set value should be equal to \<source\>:\<set_name\>
RESOLVED

**Comment by fako** [comment]
Mimetype is sometimes an empty string and when this happens the type key is missing. This in turn crashes product indexing. The type should always be something. At least it should be "unknown".
Example: https://harvester.dev.surfedushare.nl/admin/files/filedocument/76671/change/
RESOLVED

**Comment by fako** [comment]
Would be interesting to use Youtube titles as titles for the FileDocuments and if "text" is not available we can fill out "description" there. See what we want to do with copyright?
OUT OF SCOPE
