### ISSUE TITLE
Connect AnatomyTOOL

### ISSUE THREAD

**Issue by fako** [surfedushare/harvester#189]
Currently the AnatomyTOOL is only harvested by the legacy harvest process. The goal of this issue is to harvest it with the new harvest process as well. I'll write down some steps, not to tell you what to do, but to guide you into how the system works at the moment.

These steps are for preparation and you can do them on your own:
- [ ] Install the harvester repo by following its readme: https://github.com/surfedushare/harvester
- [ ] Checkout development branch

These steps look a bit weird at first, but are also necessary for preparation. We can pair code these if you want to:
- [ ] Copy anatomy_tool/models.py to sources/models/anatomy_tool.py
- [ ] Makemigrations and run migrations. Please run makemigrations with "-n anatomy_tool" or something else that's readable.
- [ ] Register the OAI-PMH Resource with the sources admin
- [ ] Copy anatomy_tool/tests/factories.py to sources/factories/anatomy_tool/extraction.py
- [ ] Copy anatomy_tool/fixtures/anatomy-tool-oaipmh.initial.0.xml to sources/fixtures/fixture.anatomy_tool.initial.0.xml
- [ ] Check that it's possible to use the factory from sources. If you call create_common_anatomy_tool_responses. Is it creating resources? Can you use resource.content? You'll need to adjust at least the body property before this actually works.
- [ ] APPLICATION_MODE=production invoke aws.sync-repository-state --push (check if others updated the fixtures before doing this)

Finally these steps will implement the actual metadata extraction for products and files. It's recommended to first work on products:
- [ ] Create an anatomy_tool.py file in \<entity-django-app\>/sources/ and add the OBJECTIVE from anatomy_tool/extraction.py. You will have to copy the extractor class as well
- [ ] Create a SEEDING_PHASES list that specifies how seeds can be created from potentially multiple resources/objectives and/or operations
- [ ] From here you can add tests similar to \<entity-django-app\>/tests/seeding/test_sharekit.py to test how extraction is functioning.

The following objective keys can be deleted/modified for new-style product objectives, because we handle the requirements for these keys differently with the new harvester setup. Tests related to these objectives can be deleted/modified.
* URL moves to files entity and extraction should be tested there
* files only need to return the URL (and files app will handle details)
* mime_type moves to files entity and extraction should be tested there
* technical_type moves to files entity and extraction should be tested there
* lowest_educational_level can be deleted
* from_youtube can be deleted
* is_restricted can be deleted
* analysis_allowed can be deleted
* any access_rights testing needs to move to files entity
* "complete_set" and "partial_set" tests can be removed. Instead we want tests like TestSharekitProductSeeding for each source and entity

There is also a list of product objective keys that will be nested under the "learning_material" or "research_product" dictionaries. Please see products/sources/sharekit.py for the syntax for these keys (they start with learning_material and research_product respectively).

**Comment by freezas** [comment]
About this bulletpoint: "technical_type moves to files entity and extraction should be tested there".
technical_type is a SEED_DEFAULT for products, so I'm a bit confused, but I'll leave it out the products for now.

**Comment by fako** [comment]
Yes, I added it as a default after this ticket was made. The default is necessary, because Sharekit sometimes want to override whatever the first file is indicating that the technical_type is. AnatomyTOOL doesn't need/use such overrides and therefor the default is fine. Technical type in the search engine will be filled by the FileDocument.
