### ISSUE TITLE
Do the metadata "no open, no share" agreements extend to Edurep and AnatomyTOOL?

### ISSUE THREAD

**Issue by fako** [surfedushare/harvester#2]
Through Publinova it became policy that if the metadata itself is not somehow "open access" (meaning it's readable, including indexable) then it's not shared by the source. So we can assume that all metadata is open access. This seems like a logical policy and it makes things a lot easier in the code, but the question is whether we can extend that to sources like Edurep and AnatomyTOOL.

**Comment by fako** [comment]
If we can agree to this policy we could completely get rid of this "inactive" seed path: https://github.com/surfedushare/search-portal/blob/acceptance/harvester/harvester/utils/extraction.py#L15-L16

**Comment by MirjamButtner** [comment]
Check and if ok add to policy. I assume the metadata is open access and can be indexed, but will check to be sure. 
If the file is open access, but has creative comments/copyright we should also be able to index it.

**Comment by fako** [comment]
Especially AnatomyTOOL currently doesn't give any information about access rights. I'm going to assume that everything that I receive from AnatomyTOOL tries to say "OpenAccess", but didn't include it into the response.

**Comment by fako** [comment]
Here's an example of an AnatomyTOOL that has copyright restrictions, but seems to be available on the internet: https://anatomytool.org/node/56176
I'll mark that as "RestrictedAccess" seems more appropriate than "OpenAccess".

**Comment by fako** [comment]
If a source gives us the metadata, then we can assume it is "open access" metadata. We'll document this on confluence.
