### ISSUE TITLE
Youtube API for previews

### ISSUE THREAD

**Issue by fako** [surfedushare/harvester#27]
### Why
As EduSources platform owner I want to fetch video previews using the YouTube API, so I have a reliable, documented and legal way to het previews for items

### Acceptance Criteria
```gherkin
Scenario: Download preview using API
Given There is a material
And the type of the material is a YouTube video
And the material does not have a preview image
And the YouTube API has been integrated
When the preview for this material is fetched 
Then the preview is stored
And the preview is associated to the matererial
But youtubedl is not used
```

While we are at it: also download transcriptions?!
Perhaps also things like title and description...

**Comment by fako** [comment]
The classic YoutubeDL script is starting to become more problematic: https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by fako** [comment]
Here's the endpoint that we need: https://developers.google.com/youtube/v3/docs/videos/list
To begin with we'll want to ask for information video by video (so a list of 1 video). For the 700 videos we have that's going to be just fine. It's later possible to refactor this into 100 videos per call, but that's a bit more involved so let's first do this.

This is the data we can extract: https://developers.google.com/youtube/v3/docs/videos#resource
From this data we'll at least need: duration and thumbnails. This is the data we currently use. Titles and descriptions are also interesting. Perhaps we can skip Tika and only do Youtube API for Youtube documents?

**Comment by fako** [comment]
Wouter vraagt na welk Google account we kunnen gebruiken.

**Comment by kallepronk** [comment]
https://github.com/surfedushare/harvester/blob/acceptance/harvester/core/models/resources/youtube_thumbnail.py#L75-L79
Can probable still be the same, everything before should be changed from youtubeDL to the new way

**Comment by kallepronk** [comment]
https://github.com/surfedushare/harvester/blob/acceptance/harvester/core/management/commands/generate_previews.py#L40-L44

**Comment by fako** [comment]
Google credentials nu beschikbaar via: https://github.com/surfedushare/infra/issues/78

**Comment by fako** [comment]
Voorbeeld van een background task die de YoutubeAPIResource zou kunnen gebruiken om video data toe te voegen aan de derivatives attribute van FileDocument: https://github.com/surfedushare/harvester/blob/development/harvester/files/tasks/metadata.py#L47-L76

**Comment by fako** [comment]
Testen voor de HttpPipelineProcessor staan hier: https://github.com/surfedushare/harvester/blob/development/harvester/core/tests/pipeline/test_http_pipeline_processor.py
Die geven een goed beeld van wat de HttpPipelineProcessor doet.

**Comment by fako** [comment]
De tasks configuratie van FileDocument moet aangepast om je background task daadwerkelijk te runnen: https://github.com/surfedushare/harvester/blob/development/harvester/files/models/datatypes/file.py#L21-L25
en
https://github.com/surfedushare/harvester/blob/development/harvester/files/models/datatypes/file.py#L31-L35

Deze assert moet sowieso veranderd. Je zou dat kunnen veranderen, de test laten falen en vervolgens aanpassen tot de tests het halen.
https://github.com/surfedushare/harvester/blob/development/harvester/files/tests/tasks/test_dispatch_document_tasks.py#L47
