### ISSUE TITLE
[EDU,PUB] Propagate modified_at that comes from source

### ISSUE THREAD

**Issue by fako** [surfedushare/harvester#294]

**Comment by peterdubbeldsurf** [comment]
Nodig voor Dashboard om gewijzigde content bij de bronsystemen duidelijk in een overzicht weer te kunnen geven.

**Comment by fako** [comment]
Format van de datetimes verschilt nogal. Soms is het alleen een datum in ISO 8601 format. Soms is het ISO 8601 met ook de tijd en soms zit zelfs de timezone offset erbij. Soms met nanoseconden en soms tot op de seconde. We kunnen dit gaan standaardiseren, maar de vraag is even hoe belangrijk dat is en waar naar toe. Europe/Amsterdam timezone? UTC? Alle dates zijn geldige ISO dates, dus in die zin voldoen ze aan de standaard, maar ze zijn niet geheel 1-op-1 te vergelijken vanwege tijdsverschillen.

**Comment by fako** [comment]
Output should become a date not a datestring

**Comment by fako** [comment]
Serializer output should parse to dates: https://docs.djangoproject.com/en/5.0/ref/utils/#module-django.utils.dateparse

**Comment by fako** [comment]
Now also available on acceptance (harvest started 1m ago)
