### ISSUE TITLE
SIA heeft onaangekondigde API wijzigingen

### ISSUE THREAD

**Issue by fako** [surfedushare/harvester#376]
En dit geeft errors: https://surf-eduservices.sentry.io/issues/4619315455/?project=4505125577228288&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=3

Als de zichtbaarheid "onzichtbaar" is. Welke status moeten wij het dan geven? Hoe gaat de frontend hierop reageren?

**Comment by peterdubbeldsurf** [comment]
Checken met Zooma, wat het gevolg van het doorgeven van status "Onbekend"? Checken met Pascal

**Comment by fako** [comment]
Dit is hoe een deleted SIA project nu doorkomt. Ben van plan dit binnenkort naar prod te brengen. Stem jij nog even af met Pascal hoe dit afgevangen gaat worden? @peterdubbeldsurf 

![Image](https://github.com/surfedushare/harvester/assets/942693/1091c939-13a3-459a-a489-0562f3ff0d66)

(bron: https://sources.acc.publinova.nl/api/v1/entities/projects/sia/?cursor=offset%7C1000%7C1000)

**Comment by fako** [comment]
Released
