### ISSUE TITLE
Create document page for "open access" policy

### ISSUE THREAD

**Issue by fako** [surfedushare/harvester#4]
How should we interpret this product? Is it open access and should we index or is it restricted and should we exclude the file from full text indexing?

![Image](https://user-images.githubusercontent.com/942693/215725200-7195ad0e-3d6f-4a4b-8be8-32040fb0888d.png)

**Comment by fako** [comment]
Here's the NL-LOM definition of access rights: https://purl.edustandaard.nl/classification_accessrights_nllom_20180530
As long as institutes wave their rights, then OpenAccess might be a valid value here.

**Comment by MirjamButtner** [comment]
Met Wouter en Dafne besproken. 

- @fako kunnen jij laten weten hoe vaak dit voorkomt? En een lijst delen met de bestanden waarbij dit zo is? 
- We laten eerst de gebruikers weten dat we van plan zijn deze regel eruit te halen. Wanneer het niet zo vaak voorkomt specifiek aan de eigenaren van deze materialen, anders aan alle gebruikers. 
- We tonen een melding bij deze bestanden in edusources dat de terms of use niet bekend zijn, of "voor dit item is geen CC licentie bekend" 
- we nemen de regel over uit de HBO kennisbank voorwaarden waarin staat dat, wanneer je een materiaal op edusources publiceert, het daarmee ook gezocht en gevonden kan worden. 

Achtergrond: 
Ze hebben al gekozen te delen. 
Sharekit veld gebruikslicentie zou niet verplicht moeten zijn - nu moeten ze een CC licentie hebben - als ze dat niet hebben zetten ze er restricted - maar het kan open access zonder CC licentie kunnen zijn 
Als we straks automatisch gaan uploaden, dan wordt het nog steeds niet automatisch gepubliceerd, dat wordt handmatig per item gedaan. 
kanalen weggooien, restricted access eruit gooien 
terms of use: yes is oud
we willen access restricties op bestanden gaan zetten
We hebben niet voor niets restricted erbij gezet. 
Als we het alleen bij het bestand zetten, dan moet bij het bestand Copyright komen te staan. 
Voor Sharekit wordt het dan niet mogelijk
Volgens het AIP zitten er geen auteursrechten op metadata 
zit geen stempel van de auteur 
de instellingen zijn eigenaar van de metadata 
houden we bij wie de metadateerder is? De creator wel, de editor niet. Creator mag het bewerken. 
Je kunt niet alles van iedereen harvesten. Er zitten filters op. Je moet een API key aanvragen? Doel moet tonen van eigen publicaties op eigen website. OM data van andere instellingen  te tonen moet toestemming gevraagd worden. 
retricted access op bestandsniveau - 
HBO kennisbank deelt open access uit - alle bestanden moeten dan op open access staan
default op edusources moet herbruikbaar zijn - anders heb je er niets aan 
Als je het alleen in kunt zien heb je er niet zoveel aan
We hebben er nu geen commerciële materialen in - maar daar zou je wel korte overnames uit mogen doen 
Default is open - maar we willen semi-open ook mogelijk maken - via single sign on. 
Niet het hoofddoel van edusources. 
Gaan we gebruikslicenties op hoofdniveau wegnemen? 
We kunnen gebruikers voor wie dit voorkomt aankondigen dat we een verandering doen waardoor deze materialen wel worden getoond. 

Bij hoeveel materialen komt dit voor? Fako vragen. Overzichtje materialen. 
Laten weten dat we dit gaan doen. 
We gaan ervan uit dat alles wat via een open kanaal gepubliceerd is ook op edusources gedeeld mag worden. 
In edusources tonen dat er geen CC licentie voor is 

Melding in edusources: terms of use niet bekend. 

Als we in Sharekit de optie uit de dropdown weghalen, dan... 
Handmatige deze materialen aanpassen in Sharekit als het er niet zoveel zijn. 

Je wil van de gebruiker weten, het is via een publiek kanaal gedeeld, en open access, maar er staat terms of use yes terwijl we niet weten welke. Wil je het dan tonen? 

public access op publicatie niveau toevoegen - 

publicatie niveau heeft alleen gebruiksrechten 

we kunnen tijdelijk een nieuwe optie toevoegen: CC, public access of wel nog restricted.
Dat vindt Dafne gek, want de kanalen bepalen of je het publiek maakt en hoe
Dus restricted moet weg
Is niet alleen voor edusources maar ook voor HBO kennisbank en Publinova

Wijziging vindt plaats aan de harvesting kant

we kunnen nu in edusources ze wel allemaal laten zien

**Comment by fako** [comment]
If we receive the metadata we assume metadata is open access.

**Comment by fako** [comment]
Things regarding other organizations then Sharekit:
- [x] Does Edurep understand open access like we do now? Some of the "unknown" copyright comes from them (Martine)
- [x] HKU has indicated that everything is "open access" with copyright "cc-by-nc-nd". Do we need to formally confirm this?

**Comment by MirjamButtner** [comment]
On https://wiki.surfnet.nl/display/EDS/Harvester+restrictions. Get editing authorization for this page. 
conditions for displaying data on edusources and Publinova
Draft a proposal to be checken by Martine, Wouter, John & Fako (in regular meeting)

**Comment by fako** [comment]
Other valid educational level values are:
* HBO - Bachelor
* HBO - Master
* WO - Bachelor
* WO - Master

These values will be normalized to WO and HBO.
For Publinova educational level is irrelevant and all values are ignored.

**Comment by MirjamButtner** [comment]
"The edusources harvester is able to harvest materials using the NL LOM standards. The harvester filters the incoming materials using a couple of rules described below. In order to be indexed by edusources, materials should comply to all of the rules." 
to
"The edusources harvester is able to harvest materials using the NL LOM standard. The harvester filters the incoming materials using the rules described below. In order to be visible in and indexed by edusources, materials should comply to all of the rules." 
When your file is fully indexed it is much more likely your document will be found. It is only fully indexed when the "access policy" is "open access". When the access policy is restricted access then we check for the copyright. 
This link defines what open, restricted and closed access mean according to NL LOM, which is consistent with Mods Didl.  
Link "https://purl.edustandaard.nl/classification_accessrights_nllom_20180530". 
Only in case of restricted access do we still look at the copyright. 
Documents with restricted access policy and non derivative (nd) copyright will not be fully indexed. 
If the document is not fully indexed but only the metadata, the document is less likely to be found.
